import React from "react";

export default function About() {
  return (
    <div style={pageStyle}>

      <div style={container}>

        {/* HEADER */}
        <h1 style={heading}>🛡️ About Ad Fraud Detection System</h1>

        {/* INTRO */}
        <div style={card}>
          <h2 style={subHeading}>📌 Project Overview</h2>
          <p style={text}>
            Ad fraud is one of the biggest challenges in digital advertising,
            causing billions of dollars in losses every year. This system is
            designed to detect fraudulent ad clicks in real-time using machine
            learning techniques.
          </p>
        </div>

        {/* PROBLEM */}
        <div style={card}>
          <h2 style={subHeading}>⚠️ Problem Statement</h2>
          <p style={text}>
            Fake clicks generated by bots, click farms, or malicious users
            can inflate ad metrics and waste advertiser budgets. Traditional
            systems fail to detect sophisticated fraud patterns effectively.
          </p>
        </div>

        {/* SOLUTION */}
        <div style={card}>
          <h2 style={subHeading}>💡 Our Solution</h2>
          <p style={text}>
            We developed a machine learning-based system that analyzes user
            behavior such as click timing, device, operating system, and IP
            patterns to identify fraudulent activity.
          </p>
        </div>

        {/* FEATURES */}
        <div style={card}>
          <h2 style={subHeading}>🚀 Key Features</h2>
          <ul style={list}>
            <li>Real-time fraud detection using ML model</li>
            <li>Interactive dashboard with fraud analytics</li>
            <li>Ad performance tracking</li>
            <li>Session-based fraud analysis</li>
            <li>IP-based fraud simulation and detection</li>
          </ul>
        </div>

        {/* TECH STACK */}
        <div style={card}>
          <h2 style={subHeading}>🛠️ Technologies Used</h2>
          <ul style={list}>
            <li>Frontend: React.js</li>
            <li>Backend: Flask (Python)</li>
            <li>Machine Learning: XGBoost</li>
            <li>Database: MongoDB / SQLite</li>
            <li>API Communication: REST APIs</li>
          </ul>
        </div>

        {/* WORKFLOW */}
        <div style={card}>
          <h2 style={subHeading}>⚙️ System Workflow</h2>
          <p style={text}>
            User clicks an ad → Click data is captured → Features are extracted →
            Sent to ML model → Model predicts fraud probability → Result stored
            and displayed in dashboard.
          </p>
        </div>

        {/* FUTURE */}
        <div style={card}>
          <h2 style={subHeading}>🔮 Future Enhancements</h2>
          <ul style={list}>
            <li>Explainable AI (XAI) for fraud decisions</li>
            <li>Automatic IP blocking for fraudulent users</li>
            <li>Integration with real ad platforms</li>
            <li>Advanced behavioral pattern tracking</li>
          </ul>
        </div>

      </div>
    </div>
  );
}

/* ---------------- STYLES ---------------- */

const pageStyle = {
  minHeight: "100vh",
  padding: "100px 40px 40px",
  background: "linear-gradient(135deg,#061418,#0f2d2f,#123c3a)",
  fontFamily: "DM Sans"
};

const container = {
  maxWidth: "900px",
  margin: "auto"
};

const heading = {
  color: "#f1f5f9",
  marginBottom: "30px"
};

const subHeading = {
  color: "#e2e8f0",
  marginBottom: "10px"
};

const text = {
  color: "#9ca3af",
  lineHeight: "1.6"
};

const list = {
  color: "#9ca3af",
  paddingLeft: "20px"
};

const card = {
  background: "rgba(255,255,255,0.05)",
  backdropFilter: "blur(12px)",
  border: "1px solid rgba(255,255,255,0.1)",
  borderRadius: "16px",
  padding: "20px",
  marginBottom: "20px",
  boxShadow: "0 10px 30px rgba(0,0,0,0.4)"
};